livery = {
	{"Mat: SA342_Camou_ADT_1", 0, "SA342_Camou_TigerM_1.dds", true},
	{"Mat: SA342_Camou_ADT_2", 0, "SA342_Camou_TigerM_2.dds", true},
	{"camou_adt_2_droppable", 0, "SA342_Camou_TigerM_2.dds", true},
	{"Mat: SA342_Camou_ADT_3", 0, "SA342_Camou_TigerM_3.dds", true},
	{"Mat: SA342_Camou_ADT_4", 0, "SA342_Camou_TigerM_4.dds", true},
	{"Mat: SA342_Camou_ADT_5", 0, "SA342_Camou_TigerM_5.dds", true},
	{"Mat: SA342_Camou_ADT_6", 0, "SA342_Camou_TigerM_6.dds", true},
	{"Mat: SA342_Camou_ADT_7", 0, "SA342_Camou_TigerM_7.dds", true},
	{"Mat: SA342_Camou_ADT_8", 0, "SA342_Camou_TigerM_8.dds", true},
	{"Mat: SA342_Camou_ADT_9", 0, "SA342_Camou_TigerM_9.dds", true},
	{"Mat: SA342_Camou_ADT_10", 0, "SA342_Camou_TigerM_10.dds", true},
	{"Mat: SA342_Camou_ADT_11", 0, "SA342_Camou_TigerM_11.dds", true},
	{"cabin floor", 0, "SA342_Camou_TigerM_11.dds", true},
	{"Mat: SA342_Camou_ADT_Wpns_1", 0, "SA342_Camou_TigerM_Wpsns_1.dds", true},
	{"Mat: SA342_Camou_ADT_Wpns_2", 0, "SA342_Camou_TigerM_Wpsns_2.dds", true},
	{"Mat: SA342_ADT_Addons", 0, "SA342_Camou_TigerM_Addons.dds", true},
	{"Mat: SA342_Camou_ADT_Addons_3", 0, "SA342_Camou_TigerM_Addons_3.dds", true},
	{"Mat: SA342_Cpit_Doors_1", 0, "SA342_Cpit_Doors_1_TigerM.dds", true},
	{"Tex: SA342L_panels_Interiors_5", 0, "SA342L_panels_Interiors_5_TigerM.dds", true},
	{"Mat: SA342_panels_Interiors_7", 0, "SA342_panels_Interiors_7_TigerM.dds", true},
	{"sticks serial numbers 1", 0, "stick empty.dds", true},
	{"sticks serial numbers 2", 0, "stick empty.dds", true},
	{"sticks serial numbers 3", 0, "stick empty.dds", true},
	{"sticks serial numbers 4", 0, "stick empty.dds", true},
	{"front big letter stick 1", 0, "stick empty.dds", true},
	{"front big letter stick 2", 0, "stick empty.dds", true},
	{"right big letter 1", 0, "stick empty.dds", true},
	{"right big letter 2", 0, "stick empty.dds", true},
	{"right big letter 3", 0, "stick empty.dds", true},
	{"left big letter 1", 0, "stick empty.dds", true},
	{"left big letter 2", 0, "stick empty.dds", true},
	{"left big letter 3", 0, "stick empty.dds", true},
	{"sticks big letters", 0, "stick empty.dds", true},
	{"bottom big letter 1", 0, "Serial_White.dds", true},
	{"bottom big letter 2", 0, "Serial_White.dds", true},
	{"bottom big letter 3", 0, "Serial_White.dds", true},
	{"serial_stick_left_1_GER", 0, "stick empty.dds", true},
	{"serial_stick_left_2_GER", 0, "stick empty.dds", true},
	{"serial_stick_left_3_GER", 0, "stick empty.dds", true},
	{"serial_stick_left_4_GER", 0, "stick empty.dds", true},
	{"serial_stick_right_1_GER", 0, "stick empty.dds", true},
	{"serial_stick_right_2_GER", 0, "stick empty.dds", true},
	{"serial_stick_right_3_GER", 0, "stick empty.dds", true},
	{"serial_stick_right_4_GER", 0, "stick empty.dds", true},
	{"right door big letter 1", 0, "Serial_White.dds", true},
	{"right door big letter 2", 0, "Serial_White.dds", true},
	{"right door big letter 3", 0, "Serial_White.dds", true},
	{"left door big letter 1", 0, "Serial_White.dds", true},
	{"left door big letter 2", 0, "Serial_White.dds", true},
	{"left door big letter 3", 0, "Serial_White.dds", true},
	{"left door big 3rd letter forward", 0, "stick empty.dds", true}
}
countries = {"FRA"}