livery = {
	{"Mat: SA342_Camou_ADT_1", 0, "SA342_Camou_ADT_1.dds", false},
	{"Mat: SA342_Camou_ADT_1", ROUGHNESS_METALLIC,"SA342_Camou_ADT_1_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_2", 0, "SA342_Camou_ADT_2.dds", false},
	{"Mat: SA342_Camou_ADT_2", ROUGHNESS_METALLIC,"SA342_Camou_ADT_2_roughmet.dds", false},
	{"camou_adt_2_droppable", 0, "SA342_Camou_ADT_2.dds", false},
	{"Mat: SA342_Camou_ADT_3", 0, "SA342_Camou_ADT_3.dds", false},
	{"Mat: SA342_Camou_ADT_3", ROUGHNESS_METALLIC,"SA342_Camou_ADT_3_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_4", 0, "SA342_Camou_ADT_4.dds", false},
	{"Mat: SA342_Camou_ADT_4", ROUGHNESS_METALLIC,"SA342_Camou_ADT_4_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_5", 0, "SA342_Camou_ADT_5.dds", false},
	{"Mat: SA342_Camou_ADT_5", ROUGHNESS_METALLIC,"SA342_Camou_ADT_5_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_6", 0, "SA342_Camou_ADT_6.dds", false},
	{"Mat: SA342_Camou_ADT_6", ROUGHNESS_METALLIC,"SA342_Camou_ADT_6_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_7", 0, "SA342_Camou_ADT_7.dds", false},
	{"Mat: SA342_Camou_ADT_7", ROUGHNESS_METALLIC,"SA342_Camou_ADT_7_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_8", 0, "SA342_Camou_ADT_8.dds", false},
	{"Mat: SA342_Camou_ADT_8", ROUGHNESS_METALLIC,"SA342_Camou_ADT_8_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_9", 0, "SA342_Camou_ADT_9.dds", false},
	{"Mat: SA342_Camou_ADT_9", ROUGHNESS_METALLIC,"SA342_Camou_ADT_9_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_10", 0, "SA342_Camou_ADT_10.dds", false},
	{"Mat: SA342_Camou_ADT_10", ROUGHNESS_METALLIC,"SA342_Camou_ADT_10_roughmet.dds", false},
	{"Mat: SA342_Camou_ADT_11", 0, "SA342_Camou_ADT_11.dds", false},
	{"Mat: SA342_Camou_ADT_11", ROUGHNESS_METALLIC,"SA342_Camou_ADT_11_roughmet.dds", false},
	{"cabin floor", 0, "SA342_Camou_ADT_11.dds", false},
	{"Mat: SA342_Camou_ADT_Wpns_1", 0, "SA342_Camou_ADT_Wpsns_1.dds", false},
	{"Mat: SA342_Camou_ADT_Wpns_2", 0, "SA342_Camou_ADT_Wpsns_2.dds", false},
	{"Mat: SA342_V2_Weapons_Optics", 0, "SA342_V2_Weapons_Optics.dds", false},
	{"Mat: SA342_V2_Weapons_Optics", ROUGHNESS_METALLIC,"SA342_V2_Weapons_Optics_roughmet.dds", false},
	{"Mat: SA342_ADT_Addons", 0, "SA342_Camou_ADT_Addons.dds", false},
	{"Mat: SA342_Camou_ADT_Addons_3", 0, "SA342_Camou_ADT_Addons_3.dds", false},
	{"Mat: SA342_ADT_Addons_2", 0, "SA342_Camou_ADT_Addons_2.dds", false},
	{"Mat: SA342_Cpit_Doors_1", 0, "SA342_Cpit_Doors_1.dds", false},
	{"Tex: SA342_panels_Interiors_5", 0, "SA342_panels_Interiors_5.dds", false},
	{"Mat: SA342_panels_Interiors_5", 0, "SA342_panels_Interiors_5.dds", false},
	{"Mat: SA342_panels_Interiors_7", 0, "SA342_panels_Interiors_7.dds", false},
	{"Mat: SA342_Camou_ADT_HOT_LCHR_Wpsns_3", 0, "SA342_Camou_HOT_LCHR_Wpsns_3.dds", false},
	{"sticks serial numbers 1", 0, "stick empty.dds", true},
	{"sticks serial numbers 2", 0, "stick empty.dds", true},
	{"sticks serial numbers 3", 0, "stick empty.dds", true},
	{"sticks serial numbers 4", 0, "stick empty.dds", true},
	{"front big letter stick 1", 0, "stick empty.dds", true},
	{"front big letter stick 2", 0, "stick empty.dds", true},
	{"right big letter 1", 0, "stick empty.dds", true},
	{"right big letter 2", 0, "stick empty.dds", true},
	{"right big letter 3", 0, "stick empty.dds", true},
	{"left big letter 1", 0, "stick empty.dds", true},
	{"left big letter 2", 0, "stick empty.dds", true},
	{"left big letter 3", 0, "stick empty.dds", true},
	{"sticks big letters", 0, "stick empty.dds", true},
	{"bottom big letter 1", 0, "stick empty.dds", true},
	{"bottom big letter 2", 0, "stick empty.dds", true},
	{"bottom big letter 3", 0, "stick empty.dds", true},
	{"serial_stick_left_1_GER", 0, "stick empty.dds", true},
	{"serial_stick_left_2_GER", 0, "stick empty.dds", true},
	{"serial_stick_left_3_GER", 0, "stick empty.dds", true},
	{"serial_stick_left_4_GER", 0, "stick empty.dds", true},
	{"serial_stick_right_1_GER", 0, "stick empty.dds", true},
	{"serial_stick_right_2_GER", 0, "stick empty.dds", true},
	{"serial_stick_right_3_GER", 0, "stick empty.dds", true},
	{"serial_stick_right_4_GER", 0, "stick empty.dds", true},
	{"right door big letter 1", 0, "stick empty.dds", true},
	{"right door big letter 2", 0, "stick empty.dds", true},
	{"right door big letter 3", 0, "stick empty.dds", true},
	{"left door big letter 1", 0, "stick empty.dds", true},
	{"left door big letter 2", 0, "stick empty.dds", true},
	{"left door big letter 3", 0, "stick empty.dds", true},
	{"left door big 3rd letter forward", 0, "stick empty.dds", true},

}
name = "TaktLWG 66"